
name: Build


on:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Build Release
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: tasker
          path: target/release/tasker